# Generated by Django 5.0.6 on 2024-08-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
